/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ovc.databasemanagement;

import com.nomis.ovc.business.ProcessMonitor;
import com.nomis.ovc.dao.DaoUtility;
import com.nomis.ovc.dao.ProcessMonitorDao;
import com.nomis.ovc.dao.ProcessMonitorDaoImpl;
import com.nomis.ovc.util.AppUtility;
import com.nomis.ovc.util.DateManager;



/**
 *
 * @author smomoh
 */
public class BackgroundProcessManager 
{
  public boolean backgroundProcessExecuted(String processName,int repeatValue)
  {
      boolean executed=false;
      try
      {
          DaoUtility util=new DaoUtility();
        //ProcessMonitorDao pmdao=new ProcessMonitorDaoImpl();
        ProcessMonitor pm=util.getProcessMonitorDaoInstance().getProcessMonitorByProcessName(processName);
        if(pm !=null && pm.getRepeatAction()>=repeatValue)
        executed=true;
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
      }
      return executed;
  }
  public boolean markBackgroundProcessAsExecuted(String processName,int repeatValue)
  {
      boolean executed=false;
      try
      {
        AppUtility appUtil=new AppUtility();
        ProcessMonitorDao pmdao=new ProcessMonitorDaoImpl();
        ProcessMonitor pm=pmdao.getProcessMonitorByProcessName(processName);
        if(pm==null)
        {
            pm=new ProcessMonitor();
            //pm.setProcessId(getUniqueRecordId());
            pm.setProcessName(processName);
            pm.setProcessStatus(1);
            pm.setAutogenerated(1);
            pm.setRepeatAction(repeatValue);
            pm.setLastModifiedDate(DateManager.getDateInstance(DateManager.getCurrentDate()));
            //pmdao.saveProcessMonitor(pm);
            System.err.println("Process with name: "+pm.getProcessName()+" executed");
        }
        if(pm !=null)
        executed=true;
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
      }
      return executed;
  }
  public String getUniqueRecordId()
    {
        AppUtility appUtil=new AppUtility();
        String uniqueId=appUtil.generateUniqueId(11);
        try
        {
            ProcessMonitorDao pmdao=new ProcessMonitorDaoImpl();
            if(pmdao.getProcessMonitorByProcessId(uniqueId) !=null)
            getUniqueRecordId();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return uniqueId;
    }
  
  public void executeBackgroundProcesses()
  {
     //executeBackgroundProcess(BackgoundProcessConstant.COMPLETE_HOUSEHOLD_WITHDRAWAL);
     //executeBackgroundProcess(BackgoundProcessConstant.REMOVE_HOUSEHOLDS_WITHOUT_OVC);
     //executeBackgroundProcess(BackgoundProcessConstant.UPDATE_WITHDRAWAL_STATUS);
     //executeBackgroundProcess(BackgoundProcessConstant.UPDATE_BIRTH_REGISTRATION);
         
     //executeBackgroundProcess(BackgoundProcessConstant.HHVA_CLEANUP);
     //executeBackgroundProcess(BackgoundProcessConstant.BASELINE_HHVA_MIGRATION);
     //executeBackgroundProcess(BackgoundProcessConstant.FOLLOWUP_HHVA_MIGRATION);
  }
  
}
